#!/usr/bin/python

def inventory_linux_services(info):
	if len(info) > 0:
		return [ (None, {}) ]

def check_linux_services(item, params, info):
	for line in info:
		c = ' '.join(line)

		if 'failed' in c:
			return (2, 'CRITICAL - there are failed services')

	return (0, "OK - there are no failed services")

check_info['linux_services'] = {
    "check_function"          : check_linux_services,
    "inventory_function"      : inventory_linux_services,
    "service_description"     : "Linux Services",
    "has_perfdata"            : False,
}
